name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build -t python-representer .
      - name: Run Docker image
        run: docker run python-representer
  
